language: go

sudo: required
services:
  - docker

go:
 - 1.3
 - 1.4
 - 1.5
 - 1.6
 - tip

env:
 - SCENARIO=false
 - SCENARIO=true

matrix:
  exclude:
    - go: 1.3
      env: SCENARIO=true
    - go: 1.4
      env: SCENARIO=true
    - go: 1.5
      env: SCENARIO=true
    - go: tip
      env: SCENARIO=true

script:
 - bash test/scenario_test/ci-scripts/travis-build-script.sh $SCENARIO

notifications:
 webhooks:
   urls:
     - https://webhooks.gitter.im/e/5a843ba64bd0f469337b
